# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
#    role_hierarchy:
#        ROLE_ADMIN:  ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
#            memory: ~
            memory:
                users:
                    ryan:
                        password: '$2y$13$8wTIGfRkU.xQgSu6wUaYR.LkKX3hYi0gLvObdZZZ3VjM7cfWydtnC'
                        roles: 'ROLE_USER'
                    admin:
                        password: testpass
                        roles: 'ROLE_ADMIN'
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
#            logout:
#                path: /logout
#                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_USER }
#
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt



